### ISSUE TITLE
Please update to Foundy VTT 11+ ver

### ISSUE THREAD

**Issue by Sawwa-Zubenko** [nachofunk/RogueTrader-FoundryVTT#9]
Please update you awesome work to Foundry VTT 11+ version

**Comment by nachofunk** [comment]
A little late, but it should work on version 11 now with update 1.0.3. It does include refactoring how ships work, which will delete any existing ships, so make sure to back up your stats accordingly. The new version has the ships as actors, which will make it better for future development with attack roles and ship combat.
